LITRevu/LITRevu/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView
import authentication.views
import review.views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "",
        LoginView.as_view(
            template_name="authentication/login.html",
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path("signup/", authentication.views.signup_page, name="signup"),
    path("home/", review.views.home, name="home"),
    path("logout/", authentication.views.logout_user, name="logout"),
    path(
        "profile_photo/upload/",
        authentication.views.upload_profile_photo,
        name="upload_profile_photo",
    ),
    path("ticket/create/", review.views.create_ticket, name="create_ticket"),
    path(
        "ticket/<int:ticket_id>/edit/",
        review.views.edit_ticket,
        name="edit_ticket",
    ),
    path(
        "ticket/<int:ticket_id>/delete/",
        review.views.delete_ticket,
        name="delete_ticket",
    ),
    path(
        "ticket/<int:ticket_id>/error_delete_ticket/",
        review.views.error_delete_ticket,
        name="error_delete_ticket",
    ),
    path(
        "ticket/<int:ticket_id>/review/create/",
        review.views.create_review,
        name="create_review",
    ),
    path(
        "ticket/<int:ticket_id>/review/<int:review_id>/edit/",
        review.views.edit_review,
        name="edit_review",
    ),
    path(
        "ticket/<int:ticket_id>/review/<int:review_id>/delete/",
        review.views.delete_review,
        name="delete_review",
    ),
    path(
        "follow-users/listing/", review.views.follow_users, name="follow_users"
    ),
    path(
        "follow-users/<str:followed_user>/delete",
        review.views.delete_follow,
        name="delete_follow",
    ),
    path(
        "ticket/create_ticket_and_review/",
        review.views.create_ticket_and_review,
        name="create_ticket_and_review",
    ),
    path("edit_post/", review.views.edit_post, name="edit_post"),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

LITRevu/review/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings
from django.db import models


class Ticket(models.Model):
    """Modèle pour les tickets.

    Ce modèle représente les tickets dans le système.
    Chaque ticket a un titre, une description, un utilisateur associé,
    une image (optionnelle) et une date de création.

    Attributes:
        title: Le titre du ticket.
        description: La description du ticket.
        user: L'utilisateur qui a créé le ticket.
        image: L'image associée au ticket.
        time_created: La date et l'heure de création du ticket.
    """

    title = models.CharField(max_length=128, name="title")
    description = models.CharField(
        max_length=2048, blank=True, name="description"
    )
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    image = models.ImageField(null=True, blank=True, name="image")
    time_created = models.DateTimeField(auto_now_add=True)

    @property
    def has_review(self):
        """Vérifie si le ticket a une critique associée.

        Returns:
            bool: True si le ticket a une critique, False sinon.
        """
        if self.reviews.count() > 0:
            return True
        else:
            return False

    def __str__(self):
        """retourne la chaine de caractere du title"""
        return f"{self.title}"


class Review(models.Model):
    """Modèle pour les critiques.

    Ce modèle représente les critiques associées aux tickets.
    Chaque critique a un ticket associé, une notation, un utilisateur associé,
    un titre, un commentaire (optionnel) et une date de création.

    Attributes:
        ticket: Le ticket associé à la critique.
        rating: La notation de la critique.
        user: L'utilisateur qui a créé la critique.
        headline: Le titre de la critique.
        body: Le commentaire de la critique.
        time_created: La date et l'heure de création de la critique.
    """

    ticket = models.ForeignKey(
        to=Ticket, on_delete=models.CASCADE, related_name="reviews"
    )
    rating = models.PositiveSmallIntegerField(
        # validates that rating must be between 0 and 5
        validators=[MinValueValidator(0), MaxValueValidator(5)],
        verbose_name="notation",
    )
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    headline = models.CharField(max_length=128, verbose_name="title")
    body = models.CharField(
        max_length=8192, blank=True, verbose_name="comments"
    )
    time_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """retourne la chaine de caractere du ticket"""
        return f"{self.ticket}"


class UserFollows(models.Model):
    """Modèle pour suivre les utilisateurs.

    Ce modèle représente les relations de suivi entre les utilisateurs.
    Chaque instance relie un utilisateur à un autre utilisateur qu'il suit.

    Attributes:
        user: L'utilisateur qui suit un autre utilisateur.
        followed_user: L'utilisateur suivi.
    """

    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="following",
    )

    followed_user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="followed_by",
    )

    class Meta:
        """Options du modèle UserFollows."""

        # garantit qu'il n'y a pas d'instances UserFollows multiples pour les
        # paires unique
        unique_together = (
            "user",
            "followed_user",
        )

LITRevu/review/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from authentication.models import User
from . import forms, models
from django.contrib import messages
from django.db.models import Q
from itertools import chain

# from django.db.models import Avg

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


@login_required
def home(request):
    current_user_id = request.user.id
    tickets = models.Ticket.objects.filter(
        Q(
            user_id__in=models.UserFollows.objects.filter(
                user_id=current_user_id
            ).values(
                "followed_user_id"
            )  # tickets des users suivis
        )
        | Q(user_id=current_user_id)  # ticket cree par l user
    )

    reviews = models.Review.objects.filter(
        Q(
            user_id__in=models.UserFollows.objects.filter(
                user_id=current_user_id
            ).values(
                "followed_user_id"
            )  # recupere les reviews ou l id user est presente parmi les user suivis
        )
        | Q(user_id=current_user_id)  # review des avis crée par l user
        | Q(
            ticket__user_id=current_user_id
        )  # reviews liés aux tickets créés par l'user
    )

    tickets_and_reviews = sorted(
        chain(tickets, reviews),
        key=lambda instance: instance.time_created,
        reverse=True,
    )

    paginator = Paginator(tickets_and_reviews, 3)  # Nombre d'éléments par page

    page_number = request.GET.get("page")
    try:
        tickets_and_reviews = paginator.page(page_number)
    except PageNotAnInteger:
        tickets_and_reviews = paginator.page(1)
    except EmptyPage:
        tickets_and_reviews = paginator.page(paginator.num_pages)

    return render(
        request,
        "review/home.html",
        context={"tickets_and_reviews": tickets_and_reviews},
    )


@login_required
def create_ticket(request):
    """Affiche le formulaire de création de ticket.

    Cette fonction affiche le formulaire permettant à l'utilisateur
    de créer un nouveau ticket.

    Args:
        request (HttpRequest): L'objet de requête HTTP Django.

    Returns:
        HttpResponse: La réponse HTTP contenant le formulaire de création de
                      ticket.

    Raises:
        Aucune exception n'est levée.
    """
    form = forms.TicketForm()
    if request.method == "POST":
        form = forms.TicketForm(request.POST, request.FILES)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.user = request.user
            ticket.save()
            return redirect("home")
    return render(request, "review/create_ticket.html", context={"form": form})


@login_required
def edit_ticket(request, ticket_id):
    """Affiche le formulaire d'édition de ticket.

    Cette fonction affiche le formulaire permettant à l'utilisateur
    de modifier un ticket existant.

    Args:
        request (HttpRequest): L'objet de requête HTTP Django.
        ticket_id (int): L'identifiant du ticket à modifier.

    Returns:
        HttpResponse: La réponse HTTP contenant le formulaire d'édition de
        ticket.

    Raises:
        Aucune exception n'est levée.
    """
    ticket = get_object_or_404(models.Ticket, id=ticket_id)
    form = forms.TicketForm(instance=ticket)
    if ticket:
        if ticket.user != request.user:
            return redirect("error_change_ticket", ticket.id)
        else:
            if request.method == "POST":
                form = forms.TicketForm(
                    request.POST, request.FILES, instance=ticket
                )
                if form.is_valid():
                    ticket_save = form.save(commit=False)
                    ticket_save.user = request.user
                    ticket_save.save()
                    return redirect("edit_post")
    return render(
        request,
        "review/edit_ticket.html",
        context={"ticket": ticket, "form": form},
    )


@login_required
def delete_ticket(request, ticket_id):
    """Supprime un ticket.

    Cette fonction permet à un utilisateur connecté de supprimer un ticket
    spécifié s'il est l'auteur du ticket. Si l'utilisateur n'est pas l'auteur
    du ticket, il sera redirigé vers une page d'erreur appropriée.

    Args:
        request (HttpRequest): L'objet HttpRequest reçu par la vue.
        ticket_id (int): L'identifiant du ticket à supprimer.

    Returns:
        HttpResponseRedirect: Redirige l'utilisateur vers la page d'accueil ou
        une autre page appropriée après la suppression du ticket.

    Raises:
        Http404: Si le ticket spécifié n'existe pas.
    """
    ticket = get_object_or_404(models.Ticket, id=ticket_id)

    # Vérifiez si l'utilisateur actuel est bien celui qui a créé le ticket
    if ticket.user != request.user:
        return redirect(
            "error_delete_ticket", ticket.id
        )  # Redirigez vers une page d'erreur appropriée

    if request.method == "POST":
        ticket.delete()
        return redirect("home")
    return render(
        request, "review/delete_ticket.html", context={"ticket": ticket}
    )


@login_required
def error_delete_ticket(request, ticket_id):
    """Affiche une erreur lors de la suppression d'un ticket.

    Cette fonction affiche une page d'erreur indiquant à l'utilisateur
    qu'il n'est pas autorisé à supprimer le ticket spécifié.

    Args:
        request (HttpRequest): L'objet HttpRequest reçu par la vue.
        ticket_id (int): L'identifiant du ticket pour lequel la suppression
        a échoué.

    Returns:
        HttpResponse: La réponse HTTP affichant la page d'erreur avec le
        ticket concerné.

    Raises:
        Http404: Si le ticket spécifié n'existe pas.
    """
    ticket = get_object_or_404(models.Ticket, id=ticket_id)
    return render(
        request, "review/error_delete_ticket.html", context={"ticket": ticket}
    )


@login_required
def ticket_detail(request, ticket_id):
    """Affiche les détails d'un ticket.

    Cette fonction récupère les détails d'un ticket spécifié à partir de son
    identifiant et les affiche sur une page dédiée.

    Args:
        request (HttpRequest): L'objet HttpRequest reçu par la vue.
        ticket_id (int): L'identifiant du ticket à afficher en détail.

    Returns:
        HttpResponse: La réponse HTTP affichant les détails du ticket sur la
        page de détail.

    Raises:
        Http404: Si le ticket spécifié n'existe pas.
    """
    ticket = get_object_or_404(models.Ticket, id=ticket_id)
    return render(
        request, "review/ticket_detail.html", context={"ticket": ticket}
    )


@login_required
def create_review(request, ticket_id):
    """Crée une nouvelle critique.

    Cette fonction permet à un utilisateur connecté de créer une nouvelle
    critique pour un ticket spécifié.

    Args:
        request (HttpRequest): L'objet HttpRequest reçu par la vue.
        ticket_id (int): L'identifiant du ticket pour lequel la critique
        est crée.

    Returns:
        HttpResponseRedirect: Redirige l'utilisateur vers la page d'accueil
        après la création de la critique.

    Raises:
        Http404: Si le ticket spécifié n'existe pas.
    """
    ticket = get_object_or_404(models.Ticket, id=ticket_id)
    form = forms.ReviewForm()
    if request.method == "POST":
        form = forms.ReviewForm(request.POST)
        print(form.errors)
        if form.is_valid():
            rating_value = int(request.POST.get("rating", 0))
            review = form.save(commit=False)
            review.user = request.user
            review.rating = rating_value
            review.ticket = ticket
            review.save()
            return redirect("home")
        else:
            # Afficher les erreurs dans le formulaire
            print(form.errors)
    return render(
        request,
        "review/create_review.html",
        context={"ticket": ticket, "form": form},
    )


@login_required
def edit_review(request, ticket_id, review_id):
    """Modifie une critique existante.

    Cette fonction permet à un utilisateur connecté de modifier une critique
    existante.

    Args:
        request (HttpRequest): L'objet HttpRequest reçu par la vue.
        ticket_id (int): L'identifiant du ticket associé à la critique.
        review_id (int): L'identifiant de la critique à modifier.

    Returns:
        HttpResponseRedirect: Redirige l'utilisateur vers la page de
        modification après avoir enregistré les modifications.

    Raises:
        Http404: Si le ticket ou la critique spécifiée n'existe pas.
    """
    review = get_object_or_404(models.Review, id=review_id)
    ticket = get_object_or_404(models.Ticket, id=ticket_id)
    if request.method == "POST":
        print("requette post", request.POST)
        form = forms.ReviewForm(request.POST, instance=review)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.ticket = ticket
            review.save()
            return redirect("edit_post")
    else:
        form = forms.ReviewForm(
            instance=review
        )  # Initialiser le formulaire avec l'instance de la critique

    return render(
        request,
        "review/edit_review.html",
        context={"ticket": ticket, "review": review, "form": form},
    )


@login_required
def delete_review(request, ticket_id, review_id):
    """Supprime une critique existante.

    Cette fonction permet à un utilisateur connecté de supprimer une critique
    existante.

    Args:
        request (HttpRequest): L'objet HttpRequest reçu par la vue.
        ticket_id (int): L'identifiant du ticket associé à la critique.
        review_id (int): L'identifiant de la critique à supprimer.

    Returns:
        HttpResponseRedirect: Redirige l'utilisateur vers la page de

LITRevu/review/templates/review/create_review.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
{% load review_extras %}
  <div class="px-5 py-2 container">
    <div class="white-background">
      <div class="px-5 py-2 container border border-2 border-dark rounded-4">
        <div class="row pt-1 pb-3">
          <h1 class="col text-center">Créer une critique</h1>
        </div>

        <div class="row pt-1 pb-3">
          <div class="px-5 py-2 container border border-2 border-dark rounded-4">
            <div class="row py-2">
              <h2 class="col text-start">
                Vous êtes en train de poster une réponse à {{ticket.user.username}}
              </h2>
            </div>
            <div class="px-5 py-2 container border border-2 border-dark rounded-4">
              <div class="row py-1">
                <div class="col text-start">
                  <h3>{% get_poster_display ticket.user %} demande une critque</h3>
                </div>
                <div class="col text-end">
                  <h4 class="fw-light fst-italic"  >postée le {{ ticket.time_created }}</h4>
                </div>
              </div>
              <div class="row py-1">
                <p class="col text-start">{{ ticket.title }}</p>
              </div>
              <div class="row py-1">
                <p class="col text-start">Description : {{ ticket.description }}</p>
              </div>
              <div class="row py-1">
                {% if ticket.image %}
                  <img
                    class="col-2 text-start border border-secondary"
                    src="{{ ticket.image.url }}"
                    alt="Image du ticket"
                    title="Image descriptive du ticket"
                    aria-label="IMAGE DU TICKET">
                {% endif %}
              </div>
            </div>
          </div>
        </div>

        <div class="row pt-1 pb-3">
          <div class="px-5 py-2 container border border-2 border-secondary">
            <div class="row py-2">
              <h3 class="col text-center">Critique</h3>
            </div>
            <form
              class="row pt-1 pb-3 justify-content-end"
              method="post"
              enctype="multipart/form-data"
            >
              {% csrf_token %}
              {{ form.non_field_errors }}
        <!-- Afficher les erreurs non liées à un champ -->
              <div class="form-group row">
                <label for="id_headline" class="col-form-label col-auto">Titre:</label>
                <div class="col-auto">{{ form.headline }}</div>
              </div>
              <div class="form-group row">
                <label  for="id_body" class="col-form-label col-auto">Description:</label>
                <div class="col-auto">{{ form.body }}</div>
              </div>

              <div class="form-group row">
                <label for="ratingInput" class="col-form-label col-auto">Notation:</label>
                <div class="col-auto" id="rating-options">
            <!-- Affichage des étoiles -->
                  <div class="rating-stars" id="ratingStars">
                    {% for i in "*****" %}
                      <span class="star"  data-rating="{{ forloop.counter }}"
                      >{{ '&#9733;' }}</span
                        >
                    {% endfor %}
                  </div>

                  <input
                    type="hidden"
                    name="rating"
                    id="ratingInput"
                    value="{{ review.rating }}"
                  />
                </div>
              </div>

              <button class="col-2 btn btn-outline-secondary" type="submit">
                Publier
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

LITRevu/review/templates/review/create_ticket.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
  <div class="px-5 py-2 container">
    <div class="white-background">
      <div class="px-5 py-2 container border border-2 border-dark rounded-4">
        <div class="row pt-1 pb-3">
          <h1 class="col text-center">Créer une demande de critique</h1>
        </div>
        <form
          class="row pt-1 pb-3 justify-content-end"
          method="post"
          enctype="multipart/form-data"
        >
          {% csrf_token %}
          {{ form|crispy }}
          <button class="col-2 btn btn-outline-secondary" type="submit">
            Publier
          </button>
        </form>
      </div>
    </div>
{% endblock content %}

LITRevu/review/templates/review/create_ticket_review.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
  <div class="px-5 py-2 container">
    <div class="white-background">
      <div class="px-5 py-2 container border border-2 border-dark rounded-4">
        <div class="row pt-1 pb-3">
          <h1 class="col text-center">Créer la demande de critique et une critique</h1>
        </div>

        <form class="row pt-1 pb-3" method="post" enctype="multipart/form-data">
          {% csrf_token %}

          <div class="px-5 py-2 container border border-2 border-dark rounded-4">
            <div class="row py-1">
              <h2 class="col text-center">Demande de critique</h2>
            </div>
            <div class="row py-1">{{ ticket_form|crispy }}</div>
          </div>

          <div class="px-5 py-2 container border border-2 border-dark rounded-4">
            <div class="row py-1">
              <h3 class="col">Critique</h3>
            </div>
            <div class="row py-1">{{ review_form|crispy }}</div>
            <div class="form-group row">
              <label for="ratingInput" class="col-form-label col-auto">Notation </label>
              <div class="col-auto" id="rating-options">
          <!-- Affichage des étoiles -->
                <div class="rating-stars" id="ratingStars">
                  {% for i in "*****" %}
                    <span class="star" data-rating="{{ forloop.counter }}"
                    >{{ '&#9733;' }}</span
                      >
                  {% endfor %}
                </div>

                <input
                  type="hidden"
                  name="rating"
                  id="ratingInput"
                  value="{{ review.rating }}"
                />
              </div>
            </div>
            <div class="row py-1 justify-content-end">
              <button class="col-2 btn btn-outline-secondary" type="submit">
                Publier
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

LITRevu/review/templates/review/delete_follow.html
{% extends 'base.html' %}
{% block content %}
  <div class="px-5 py-2 container">
    <div class="white-background">
      <div class="px-5 py-2 container border border-2 border-dark rounded-4">
        <div class="row pt-1 pb-3">
          <h1 class="col text-center">
            Suppression de l'abonnement avec {{ followed_user}}
          </h1>
        </div>
        <div class="row py-1">
          <p class="col text-center">
            Êtes-vous sûr de vouloir supprimer votre abonnement ?
          </p>
        </div>
        <form class="row py-1 justify-content-center" method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button class="col-2 btn btn-outline-secondary me-3" type="submit">
            Oui
          </button>
          <a
            class="col-2 btn btn-outline-secondary ms-3"
            href="{% url 'follow_users' %}"
          >Non</a
            >
          </form>
        </div>
      </div>
    </div>
{% endblock content %}

LITRevu/review/templates/review/delete_review.html
{% extends 'base.html' %}
{% block content %}
  <div class="px-5 py-2 container">
    <div class="white-background">
      <div class="px-5 py-2 container border border-2 border-dark rounded-4">
        <div class="row pt-1 pb-3">
          <h1 class="col text-center">
            Suppression de la critique concernant la demande de critique sur {{ ticket.title }}
          </h1>
        </div>
        <div class="row py-1">
          <p class="col text-center">
            Êtes-vous sûr de vouloir supprimer cette critique ?
          </p>
        </div>
        <form class="row py-1 justify-content-center" method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button class="col-2 btn btn-outline-secondary me-3" type="submit">
            Oui
          </button>
          <a class="col-2 btn btn-outline-secondary ms-3" href="{% url 'post_edit' %}"
          >Non</a
            >
          </form>
        </div>
      </div>
    </div>
{% endblock content %}

LITRevu/review/templates/review/delete_ticket.html
{% extends 'base.html' %}
{% block content %}
  <div class="px-5 py-2 container">
    <div class="white-background">
      <div class="px-5 py-2 container border border-2 border-dark rounded-4">
        <div class="row pt-1 pb-3">
          <h1 class="col text-center">
            Suppression de la demande de critique : {{ ticket.title }} postée par : {{ ticket.user.username }}
          </h1>
        </div>
        <div class="row py-1">
          <p class="col text-center">
            Êtes-vous sûr de vouloir supprimer ce post ?
          </p>
        </div>
        <form class="row py-1 justify-content-center" method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button class="col-2 btn btn-outline-secondary me-3" type="submit">
            Oui
          </button>
          <a class="col-2 btn btn-outline-secondary ms-3" href="{% url 'home' %}"
          >Non</a
            >
          </form>
        </div>
      </div>
    </div>
{% endblock content %}

LITRevu/review/templates/review/edit_post.html
{% extends 'base.html' %}
{% load review_extras %}
{% block content %}
{% load static %}

  <div class="container text-center px-5">
    <div class="white-background">
      <div class="row py-4">
        <h1>Mes Posts</h1>
      </div>
      <div id="ticketsAndReviewsContainer">
      {% for instance in tickets_and_reviews %}
        {% if instance|model_type == 'Ticket' %}
          <div class="row px-5 py-4">
            {% include 'review/partials/ticket_post_edit.html' with ticket=instance %}
          </div>
        {% elif instance|model_type == 'Review' %}
          <div class="row px-5 py-4">
            {% include 'review/partials/review_post_edit.html' with review=instance %}
          </div>
        {% endif %}
      {% endfor %}
    </div>
      {% if tickets_and_reviews.has_next %}
          <div class="row justify-content-center py-4">
            <button id="loadMoreBtn" class="col-2 btn btn-outline-secondary me-3">Afficher plus</button>
          </div>
        {% endif %}
    </div>
  </div>
{% endblock content%}

LITRevu/review/templates/review/edit_review.html
{% extends 'base.html' %}
{% block content %}
{% load review_extras %}
{% load crispy_forms_tags %}
  <div class="px-5 py-2 container">
    <div class="white-background">
      <div class="row pt-1 pb-3">
        <h1 class="col text-center">
          Modification de la critique concernant la demande de critique : {{ ticket.title }}
        </h1>
      </div>

      <div class="row pt-1 pb-3">
        <div class="px-5 py-2 container border border-2 border-dark rounded-4">
          <div class="row py-2">
            <h2 class="col text-start">
              Vous êtes en train de poster en réponse à {{ticket.user}}
            </h2>
          </div>
          <div class="px-5 py-2 container border border-2 border-dark rounded-4">
            <div class="row py-1">
              <h3 class="col fs-5 text-start">
                Critique demandée par {% get_poster_display ticket.user %}
              </h3>
              <h4 class="col text-end fw-light fst-italic">
                édité le {{ ticket.time_created }}
              </h4>
            </div>
            <div class="row py-1">
              <p class="col text-start">{{ ticket.title }}</p>
            </div>
            <div class="row py-1">
              <p class="col text-start">Description : {{ ticket.description }}</p>
            </div>
            <div class="row py-1">
              {% if ticket.image %}
                <img
                  class="col-2 text-start border border-secondary"
                  src="{{ ticket.image.url }}"
                  alt="Image de la review"
                  title="Image descriptive de la review"
                  aria-label="IMAGE DE LA REVIEW"
                />
              {% endif %}
            </div>
          </div>
        </div>
      </div>

      <div class="row pt-1 pb-3">
        <div class="px-5 py-2 container border border-2 border-dark rounded-4">
          <div class="row py-2">
            <h3 class="col text-center">Critique</h3>
          </div>
          <form
            class="row pt-1 pb-3 justify-content-end"
            method="post"
            enctype="multipart/form-data"
          >
            {% csrf_token %}
            {{ form.headline.label_tag }}
            {{ form.headline }}
            <br />
            {{ form.body.label_tag }}
            {{ form.body }}
            <br />

        <!-- Affichage des étoiles -->
            <div class="rating-stars" id="ratingStars">
              {% for i in "*****" %}
                <span class="star" data-rating="{{ forloop.counter }}"
                >{{ '&#9733;' }}</span
                  >
              {% endfor %}
            </div>

            <input
              type="hidden"
              name="rating"
              id="ratingInput"
              value="{{ review.rating }}"
            />
            <button class="col-2 btn btn-outline-secondary" type="submit">
              Modifier
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

LITRevu/review/templates/review/edit_ticket.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
  <div class="px-5 py-2 container">
    <div class="white-background">
      <div class="px-5 py-2 container border border-2 border-dark rounded-4">
        <div class="row pt-1 pb-3">
          <h1 class="col text-center">
            Modification du ticket sur {{ ticket.title }}
          </h1>
        </div>
        <form
          class="row pt-1 pb-3 justify-content-end"
          method="post"
          enctype="multipart/form-data"
        >
          {% csrf_token %}
          {{ form|crispy }}
          <button class="col-2 btn btn-outline-secondary" type="submit">
            Modifier
          </button>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

LITRevu/review/templates/review/error_delete_ticket.html
{% extends 'base.html' %}
{% block content %}
  <div class="px-5 py-2 container">
    <div class="row pt-1 pb-3">
      <h2 class="col text-start">Erreur de modification d'un ticket</h2>
    </div>
    <div class="row py-1">
      <p class="col text-start">
        Seul le créateur du ticket peut modifier ou supprimer ce ticket.
      </p>
    </div>
    <div class="row py-1">
      <p class="col text-start">
        Vous n'êtes pas le créateur de ce ticket. Son créateur est {{ ticket.user
        }}.
      </p>
    </div>
    <div class="row py-1 justify-content-center">
      <a class="col-2 btn btn-outline-secondary" href="{% url 'home' %}"
      >Retour au flux</a
        >
      </div>
    </div>
{% endblock content %}